run:
  go: "1.19"

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - gocyclo
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - rowserrcheck
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace

issues:
  exclude-rules:
    - linters:
        - gosec
      text: "(G501|G401|G505):"
