linters:
  enable:
    - bodyclose
    - goimports
    - goprintffuncname
    - gosec
    - interfacer
    - misspell
    - rowserrcheck
    - unconvert
    - whitespace

issues:
  exclude-rules:
    - linters:
        - gosec
      text: "(G501|G401):"
