# GoReleaser config
project_name: navidrome

before:
  hooks:
    - go-bindata -fs -prefix resources -tags embed -ignore="\\\*.go" -pkg resources -o resources/embedded_gen.go resources/...
    - go-bindata -fs -prefix ui/build -tags embed -nocompress -pkg assets -o assets/embedded_gen.go ui/build/...

builds:
  - id: navidrome_darwin
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -tags=embed
    ldflags:
      - -X github.com/deluan/navidrome/consts.gitSha={{.ShortCommit}} -X github.com/deluan/navidrome/consts.gitTag={{.Version}}

  - id: navidrome_linux_amd64
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=embed
    ldflags:
      - "-extldflags '-static'"
      - -X github.com/deluan/navidrome/consts.gitSha={{.ShortCommit}} -X github.com/deluan/navidrome/consts.gitTag={{.Version}}

  - id: navidrome_linux_arm
    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabi-gcc-5
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 5
      - 6
      - 7
    flags:
      - -tags=embed
    ldflags:
      - "-extldflags '-static'"
      - -X github.com/deluan/navidrome/consts.gitSha={{.ShortCommit}} -X github.com/deluan/navidrome/consts.gitTag={{.Version}}

  - id: navidrome_linux_arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc-5
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -tags=embed
    ldflags:
      - "-extldflags '-static'"
      - -X github.com/deluan/navidrome/consts.gitSha={{.ShortCommit}} -X github.com/deluan/navidrome/consts.gitTag={{.Version}}

  - id: navidrome_windows_i686
    env:
      - CGO_ENABLED=1
      - CC=i686-w64-mingw32-gcc
      - CXX=i686-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - 386
    flags:
      - -tags=embed
    ldflags:
      - "-extldflags '-static'"
      - -X github.com/deluan/navidrome/consts.gitSha={{.ShortCommit}} -X github.com/deluan/navidrome/consts.gitTag={{.Version}}

  - id: navidrome_windows_x64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -tags=embed
    ldflags:
      - "-extldflags '-static'"
      - -X github.com/deluan/navidrome/consts.gitSha={{.ShortCommit}} -X github.com/deluan/navidrome/consts.gitTag={{.Version}}

archives:
  - format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"

release:
  draft: true

changelog:
  # sort: asc
  filters:
    exclude:
      - "^docs:"
