blank_issues_enabled: false
contact_links:
  - name: Support and Feature requests
    url: https://github.com/navidrome/navidrome/discussions
    about: This is the place to ask questions and to share ideas.
