name: Release
on:
  push:
    tags:
      - "*"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Unshallow
        run: git fetch --prune --unshallow

      - uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: Build UI
        run: |
          cd ui
          npm ci
          npm run build

      - name: Run GoReleaser
        uses: docker://deluan/ci-goreleaser:1.14.1-1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: goreleaser release --rm-dist
