name: Release
on:
  push:
    branches:
      - master
    tags:
      - "v*"
jobs:
  js:
    name: Build JS bundle
    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13

      - uses: actions/cache@v1
        id: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('ui/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: npm install dependencies
        run: |
          cd ui
          npm ci

      - name: npm build
        run: |
          cd ui
          npm run build

      - uses: actions/upload-artifact@v1
        with:
          name: js-bundle
          path: ui/build

  binaries:
    name: Binaries
    if: startsWith(github.ref, 'refs/tags/')
    needs: [js]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - uses: actions/download-artifact@v1
        with:
          name: js-bundle
          path: ui/build

      - name: Run GoReleaser
        uses: docker://deluan/ci-goreleaser:1.14.1-1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: goreleaser release --rm-dist

  docker:
    name: Docker images
    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
    needs: [js]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - uses: actions/checkout@v1

      - uses: actions/download-artifact@v1
        with:
          name: js-bundle
          path: ui/build

      - name: Build the Docker image and push
        env:
          DOCKER_IMAGE: deluan/deluan
          DOCKER_PLATFORM: linux/amd64,linux/arm/v7,linux/arm64
        run: |
          echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
          docker buildx build --platform ${DOCKER_PLATFORM} `.github/workflows/docker-tags.sh` -f .github/workflows/Dockerfile.pipeline --push .
